-- Add location and SES variables to students
ALTER TABLE public.students 
ADD COLUMN IF NOT EXISTS nisn TEXT,
ADD COLUMN IF NOT EXISTS father_edu TEXT,
ADD COLUMN IF NOT EXISTS mother_edu TEXT,
ADD COLUMN IF NOT EXISTS father_job TEXT,
ADD COLUMN IF NOT EXISTS mother_job TEXT,
ADD COLUMN IF NOT EXISTS village TEXT,
ADD COLUMN IF NOT EXISTS district TEXT,
ADD COLUMN IF NOT EXISTS regency TEXT,
ADD COLUMN IF NOT EXISTS province TEXT;

-- Add fields to users (teachers)
ALTER TABLE public.users
ADD COLUMN IF NOT EXISTS kode_guru TEXT,
ADD COLUMN IF NOT EXISTS nip TEXT,
ADD COLUMN IF NOT EXISTS gender gender,
ADD COLUMN IF NOT EXISTS birth_date DATE,
ADD COLUMN IF NOT EXISTS village TEXT,
ADD COLUMN IF NOT EXISTS district TEXT,
ADD COLUMN IF NOT EXISTS regency TEXT,
ADD COLUMN IF NOT EXISTS province TEXT;
