-- Add gemini_api_key to system_settings
ALTER TABLE public.system_settings 
ADD COLUMN IF NOT EXISTS gemini_api_key text;

-- Table for AI analysis jobs / graph runs
CREATE TABLE public.ai_analysis_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
  prompt_tokens integer DEFAULT 0,
  completion_tokens integer DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  error_message text,
  requested_by uuid REFERENCES public.users(id),
  CONSTRAINT ai_analysis_jobs_pkey PRIMARY KEY (id)
);

-- Table for AI knowledge nodes
CREATE TABLE public.ai_knowledge_nodes (
  id text NOT NULL, -- ID generated by AI or custom ID (e.g., node_1, problem_literasi)
  job_id uuid NOT NULL REFERENCES public.ai_analysis_jobs(id) ON DELETE CASCADE,
  type text NOT NULL, -- e.g., 'problem', 'solution', 'root_cause', 'outcome'
  label text NOT NULL,
  description text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ai_knowledge_nodes_pkey PRIMARY KEY (id, job_id)
);

-- Table for AI knowledge edges
CREATE TABLE public.ai_knowledge_edges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL REFERENCES public.ai_analysis_jobs(id) ON DELETE CASCADE,
  source_node_id text NOT NULL,
  target_node_id text NOT NULL,
  label text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ai_knowledge_edges_pkey PRIMARY KEY (id),
  CONSTRAINT fk_source_node FOREIGN KEY (source_node_id, job_id) REFERENCES public.ai_knowledge_nodes(id, job_id) ON DELETE CASCADE,
  CONSTRAINT fk_target_node FOREIGN KEY (target_node_id, job_id) REFERENCES public.ai_knowledge_nodes(id, job_id) ON DELETE CASCADE
);

-- RLS
ALTER TABLE public.ai_analysis_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_knowledge_nodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_knowledge_edges ENABLE ROW LEVEL SECURITY;

-- Super Admin Policies
CREATE POLICY super_admin_all_ai_jobs ON public.ai_analysis_jobs
  FOR ALL USING (public.jwt_user_role() = 'super_admin');

CREATE POLICY super_admin_all_ai_nodes ON public.ai_knowledge_nodes
  FOR ALL USING (public.jwt_user_role() = 'super_admin');

CREATE POLICY super_admin_all_ai_edges ON public.ai_knowledge_edges
  FOR ALL USING (public.jwt_user_role() = 'super_admin');
